import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/Sidebar/Sidebar";
import { Titlebar } from "./components/Titlebar";
import { TauriPlatformInit } from "./utils/tauriPlatformInit";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full" data-theme="cyberpunk">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex flex-col overflow-hidden bg-neutral-950`}
            >
                <ToastContainer
                    style={{ marginTop: "40px" }}
                />
                <TauriPlatformInit />
                <Titlebar />
                <div className="flex flex-row flex-1 overflow-hidden">
                    <Sidebar />
                    {children}
                </div>
            </body>
        </html>
    );
}
